id: I30FCF35F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T21:52:29+00:00'
last_modified: '2022-06-08T06:28:00.025162+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS17557
  title: རྗེ་བློ་གསལ་ཚང་གི་བསླབ་མགུར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    8F37:
      image_group_id: I8LS17568
      title: ''
      total_pages: 32
      order: 1
      base_file: 8F37.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
