id: P006671
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 12:14:58.450834
source_metadata:
  id: bdr:W8LS17557
  title: རྗེ་བློ་གསལ་ཚང་གི་བསླབ་མགུར།
  author: ''
  volumes:
    5901f4c9fe4d48a3b416fcd53411a68a:
      image_group_id: I8LS17568
      title: ''
      volume_number: 1
      total_pages: 32
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
